---
abstract: 'installs your dist after releasing'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-InstallRelease
no_index:
  directory:
    - corpus
requires:
  Carp: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::Plugin: 0
  File::pushd: 0
  Moose: 0
  autodie: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-InstallRelease/issues
  homepage: http://p3rl.org/Dist::Zilla::Plugin::InstallRelease
  repository: git://github.com/doherty/Dist-Zilla-Plugin-InstallRelease.git
version: 0.008
